# Generated by Django 2.2 on 2021-04-18 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='user_trips',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_trips', to='buddy_app.User'),
            preserve_default=False,
        ),
    ]
