# Generated by Django 2.2 on 2021-04-18 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_app', '0002_trip_user_trips'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='user_trips',
            new_name='user_trip',
        ),
    ]
